-- ============================================================
-- Learn-AI  —  StudySet Phase 1
-- Replaces the stub study_sets / study_concepts tables from
-- 001_initial.sql with the full Phase 1 schema.
--
-- Safe to run on a fresh DB or one that already ran 001.
-- ============================================================


-- ── Drop all studyset tables (safe re-run) ──────────────────
-- Order matters: children before parents.
DROP TABLE IF EXISTS study_card_reviews CASCADE;
DROP TABLE IF EXISTS study_flashcards   CASCADE;
DROP TABLE IF EXISTS study_concepts     CASCADE;
DROP TABLE IF EXISTS study_materials    CASCADE;
DROP TABLE IF EXISTS study_sets         CASCADE;


-- ── study_sets ───────────────────────────────────────────────
-- One row per topic / book / chapter a student is studying.
CREATE TABLE study_sets (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID REFERENCES users(id) ON DELETE CASCADE,
    session_id   UUID,                          -- anonymous users
    title        TEXT NOT NULL,
    subject      TEXT,
    description  TEXT,
    summary      TEXT,                          -- AI-generated 2-3 sentence overview
    status       TEXT NOT NULL DEFAULT 'empty', -- empty | processing | ready | failed
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_study_sets_user_id    ON study_sets(user_id);
CREATE INDEX idx_study_sets_session_id ON study_sets(session_id);


-- ── study_materials ──────────────────────────────────────────
-- One row per uploaded PDF (a study set can have multiple files).
CREATE TABLE study_materials (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    study_set_id UUID NOT NULL REFERENCES study_sets(id) ON DELETE CASCADE,
    filename     TEXT NOT NULL DEFAULT 'upload.pdf',
    file_url     TEXT,                          -- R2 permanent public URL
    raw_text     TEXT,                          -- full extracted text (used for grounded chat)
    page_count   INT,
    char_count   INT,
    status       TEXT NOT NULL DEFAULT 'pending', -- pending | processing | ready | failed
    error_msg    TEXT,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_study_materials_set_id ON study_materials(study_set_id);


-- ── study_concepts ───────────────────────────────────────────
-- Key concepts extracted by GPT-4o from the uploaded material.
CREATE TABLE study_concepts (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    study_set_id UUID NOT NULL REFERENCES study_sets(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    definition   TEXT NOT NULL DEFAULT '',      -- concise 1-2 sentence definition
    explanation  TEXT,                          -- deeper 2-4 sentence explanation
    order_index  INT NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_study_concepts_set_id ON study_concepts(study_set_id);


-- ── study_flashcards ─────────────────────────────────────────
-- Term→definition or question→answer cards generated by GPT-4o.
CREATE TABLE study_flashcards (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    study_set_id UUID NOT NULL REFERENCES study_sets(id) ON DELETE CASCADE,
    concept_id   UUID REFERENCES study_concepts(id) ON DELETE SET NULL,
    front        TEXT NOT NULL,
    back         TEXT NOT NULL,
    order_index  INT NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_study_flashcards_set_id ON study_flashcards(study_set_id);


-- ── study_card_reviews ───────────────────────────────────────
-- One row per flashcard review session.
-- rating: 1=again  2=hard  3=good  4=easy  (SM-2 compatible)
CREATE TABLE study_card_reviews (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    flashcard_id UUID NOT NULL REFERENCES study_flashcards(id) ON DELETE CASCADE,
    rating       INT NOT NULL CHECK (rating BETWEEN 1 AND 4),
    reviewed_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_study_card_reviews_user ON study_card_reviews(user_id);
CREATE INDEX idx_study_card_reviews_card ON study_card_reviews(flashcard_id);
