-- ============================================================
-- Sprint 0: Institutions, teacher accounts, invite system
-- ============================================================

-- Role column on users (student by default)
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_type TEXT NOT NULL DEFAULT 'student';
-- values: 'student' | 'teacher' | 'institution_admin' | 'super_admin'

-- ── Institutions ─────────────────────────────────────────────
CREATE TABLE institutions (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name         TEXT NOT NULL,
  type         TEXT NOT NULL,          -- school | tuition_center | university | coaching
  email_domain TEXT,                   -- e.g. 'helsinki-hs.edu' for auto-verify
  country      TEXT,
  plan         TEXT NOT NULL DEFAULT 'trial',  -- trial | pro | enterprise
  max_teachers INT  NOT NULL DEFAULT 5,
  max_students INT  NOT NULL DEFAULT 50,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Who belongs to which institution
CREATE TABLE institution_members (
  institution_id UUID REFERENCES institutions(id) ON DELETE CASCADE,
  user_id        UUID REFERENCES users(id)        ON DELETE CASCADE,
  role           TEXT NOT NULL,          -- admin | teacher | student
  status         TEXT NOT NULL DEFAULT 'active',  -- active | suspended | pending
  invited_by     UUID REFERENCES users(id),
  joined_at      TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (institution_id, user_id)
);

CREATE INDEX idx_institution_members_user ON institution_members(user_id);

-- ── Standalone teacher invite codes ──────────────────────────
-- Generated by super_admin, consumed once by a teacher applicant
CREATE TABLE teacher_invites (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code       TEXT UNIQUE NOT NULL DEFAULT upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8)),
  email      TEXT,          -- pre-assigned to specific email, NULL = open invite
  note       TEXT,          -- super admin note (e.g. "Helsinki HS physics teacher")
  created_by UUID REFERENCES users(id),
  used_by    UUID REFERENCES users(id),
  used_at    TIMESTAMPTZ,
  expires_at TIMESTAMPTZ DEFAULT NOW() + INTERVAL '30 days',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Pending applications (before super_admin approves) ───────
CREATE TABLE teacher_applications (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type         TEXT NOT NULL,   -- standalone | institution
  -- common fields
  name         TEXT NOT NULL,
  email        TEXT NOT NULL,
  school_name  TEXT,
  subject      TEXT,
  message      TEXT,            -- optional note from applicant
  -- institution-only fields
  inst_type    TEXT,            -- school | tuition_center | university | coaching
  country      TEXT,
  est_teachers INT,
  est_students INT,
  email_domain TEXT,
  -- status
  status       TEXT NOT NULL DEFAULT 'pending',  -- pending | approved | rejected
  reviewed_by  UUID REFERENCES users(id),
  reviewed_at  TIMESTAMPTZ,
  reject_reason TEXT,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_teacher_applications_status ON teacher_applications(status);
CREATE INDEX idx_teacher_applications_email  ON teacher_applications(email);
