const CURL = `curl -X POST https://api.learnx-ai.com/api/public/v1/videos/generate \\
  -H "Authorization: Bearer $LEARNX_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "topic": "Newton'"'"'s laws of motion",
    "subject": "physics",
    "language": "en",
    "aspect_ratio": "16:9"
  }'

# -> {"video_id": 238, "status": "pending"}

curl https://api.learnx-ai.com/api/public/v1/videos/238 \\
  -H "Authorization: Bearer $LEARNX_API_KEY"

# -> {"status": "completed", "video_url": "https://...", ...}`;

const PYTHON = `import os
import time
import requests

API_KEY = os.environ["LEARNX_API_KEY"]
BASE = "https://api.learnx-ai.com/api/public/v1"
headers = {"Authorization": f"Bearer {API_KEY}"}

resp = requests.post(f"{BASE}/videos/generate", headers=headers, json={
    "topic": "Newton's laws of motion",
    "subject": "physics",
    "language": "en",
    "aspect_ratio": "16:9",
})
video_id = resp.json()["video_id"]

while True:
    status = requests.get(f"{BASE}/videos/{video_id}", headers=headers).json()
    if status["status"] in ("completed", "complete", "failed"):
        break
    time.sleep(5)

print(status["video_url"])`;

const NODE = `const API_KEY = process.env.LEARNX_API_KEY;
const BASE = "https://api.learnx-ai.com/api/public/v1";

const { video_id } = await fetch(\`\${BASE}/videos/generate\`, {
  method: "POST",
  headers: {
    Authorization: \`Bearer \${API_KEY}\`,
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    topic: "Newton's laws of motion",
    subject: "physics",
    language: "en",
    aspect_ratio: "16:9",
  }),
}).then((r) => r.json());

let status;
do {
  await new Promise((r) => setTimeout(r, 5000));
  status = await fetch(\`\${BASE}/videos/\${video_id}\`, {
    headers: { Authorization: \`Bearer \${API_KEY}\` },
  }).then((r) => r.json());
} while (!["completed", "complete", "failed"].includes(status.status));

console.log(status.video_url);`;

function CodeBlock({ code }: { code: string }) {
  return (
    <pre
      className="rounded-lg border p-4 text-xs overflow-x-auto mono leading-relaxed"
      style={{ borderColor: "var(--border)", background: "var(--surface-soft)" }}
    >
      <code>{code}</code>
    </pre>
  );
}

export default function DocsPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-12">
      <h1 className="text-2xl font-semibold mb-2">API reference</h1>
      <p className="text-sm mb-10" style={{ color: "var(--text-soft)" }}>
        Three endpoints, all authenticated with{" "}
        <code className="mono text-xs px-1.5 py-0.5 rounded" style={{ background: "var(--surface-soft)" }}>
          Authorization: Bearer &lt;api_key&gt;
        </code>
        .
      </p>

      <div className="flex flex-col gap-8 mb-12">
        {[
          {
            method: "POST",
            path: "/api/public/v1/videos/generate",
            desc: "Starts a multi-modal video render. Body: topic (required), subject, language, aspect_ratio.",
          },
          {
            method: "GET",
            path: "/api/public/v1/videos/{id}",
            desc: "Poll for render status. video_url and thumbnail_url are populated once complete.",
          },
          {
            method: "GET",
            path: "/api/public/v1/videos",
            desc: "Lists every video generated by the calling key.",
          },
        ].map((e) => (
          <div key={e.path} className="rounded-xl border p-4" style={{ borderColor: "var(--border)", background: "var(--surface)" }}>
            <div className="flex items-center gap-2 mono text-sm mb-2">
              <span
                className="text-xs font-semibold px-2 py-0.5 rounded"
                style={{
                  background: e.method === "GET" ? "var(--approved-bg)" : "var(--accent-soft)",
                  color: e.method === "GET" ? "var(--approved)" : "var(--accent-ink)",
                }}
              >
                {e.method}
              </span>
              {e.path}
            </div>
            <p className="text-sm" style={{ color: "var(--text-soft)" }}>{e.desc}</p>
          </div>
        ))}
      </div>

      <h2 className="text-lg font-medium mb-4">curl</h2>
      <div className="mb-8">
        <CodeBlock code={CURL} />
      </div>

      <h2 className="text-lg font-medium mb-4">Python</h2>
      <div className="mb-8">
        <CodeBlock code={PYTHON} />
      </div>

      <h2 className="text-lg font-medium mb-4">Node / JavaScript</h2>
      <div className="mb-8">
        <CodeBlock code={NODE} />
      </div>
    </div>
  );
}
